id: I5FA1472F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T19:18:03+00:00'
last_modified: '2022-06-08T05:54:59.690489+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD159411
  title: ཕུར་ལྕོག་ངག་དབང་བྱམས་པའི་གསུང་འབུམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    1B26:
      image_group_id: I2PD18480
      title: ''
      total_pages: 664
      order: 1
      base_file: 1B26.txt
    158B:
      image_group_id: I2PD18481
      title: ''
      total_pages: 662
      order: 2
      base_file: 158B.txt
    4AA0:
      image_group_id: I2PD18482
      title: ''
      total_pages: 654
      order: 3
      base_file: 4AA0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
